Algoritmo "lacoRepeticao numero 1 ao 50"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que exibe o número 1 ao 50
// Autor(a)    : Tainy Souza
// Data atual  : 23/09/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contadora<50 faca
   contadora<- contadora+1
   Escreval(contadora)
   fimenquanto


Fimalgoritmo